server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: twofa-api-demo
  web:
    resources:
      static-locations: classpath:/static/,classpath:/twofa/

management:
  endpoints:
    web:
      base-path: /twofa/actuator